### ISSUE TITLE
关于noniid-#label2数据划分每次运行程序划分的结果都不一样的问题

### ISSUE THREAD

**Issue by wangbaiqi355920251** [Xtra-Computing/NIID-Bench#7]
你好，非常感谢你提供的代码。我有个问题想请问一下，使用noniid-#label2划分数据时，每次程序运行得到的结果都不一样，无法重复上一次的实验数据划分。希望能解答一下，万分感谢

**Comment by sjtudyq** [comment]
Thanks for your question. 

Yes, we also find this is a problem. After examining the code, we find that it is because we use random.randint(). This seems not following the np.random.seed(). To solve it, we need to set seed for all these functions.
```
np.random.seed()
torch.manual_seed()
random.seed()
```
We have added them in **experiments.py**. After that, the partition of noniid-#label2 is fixed. You can experiment on exactly the same partition then.

Thanks again for pointing it out and help improving our project.

**Comment by wangbaiqi355920251** [comment]
感谢回复，问题已经得到解决
